# Generated by Django 2.2.27 on 2022-06-17 13:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('Save_code', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2022, 6, 17, 22, 27, 4, 927057), help_text='create date: ')),
                ('line', models.TextField()),
                ('circle', models.TextField()),
                ('rectangle', models.TextField()),
                ('offset', models.TextField()),
                ('saved_image', models.ImageField(upload_to='upload/')),
            ],
        ),
        migrations.CreateModel(
            name='discuss_borad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('product_code', models.TextField()),
                ('post_date', models.DateTimeField(default=datetime.datetime(2022, 6, 17, 22, 27, 4, 925056), help_text='create date: ')),
                ('command', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='image_album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='product_images_album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='product_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.TextField()),
                ('main_image', models.BooleanField()),
                ('Product_image', models.ImageField(upload_to='Product_images')),
                ('album', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.product_images_album')),
            ],
        ),
        migrations.CreateModel(
            name='product_borad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('product_code', models.TextField()),
                ('Create_Date', models.DateTimeField(default=datetime.datetime(2022, 6, 17, 22, 27, 4, 925056), help_text='create date: ')),
                ('Product_delta', models.TextField()),
                ('Product_image', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='app.product_images_album')),
                ('User_command', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app.discuss_borad')),
            ],
            options={
                'permissions': (('can_add', 'add'),),
            },
        ),
        migrations.CreateModel(
            name='Image_import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Process_type', models.TextField()),
                ('Image', models.ImageField(upload_to='Pre-Image')),
                ('album', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.image_album')),
            ],
        ),
    ]
