# Generated by Django 2.2.27 on 2022-06-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='diagram',
        ),
    ]
