# Generated by Django 2.2.27 on 2022-06-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_diagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='diagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('line', models.TextField()),
                ('circle', models.TextField()),
                ('rectangle', models.TextField()),
                ('offset', models.TextField()),
            ],
        ),
    ]
