# Generated by Django 2.2.27 on 2022-06-03 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_diagram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagram',
            old_name='type',
            new_name='username',
        ),
        migrations.AddField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='create date: '),
            preserve_default=False,
        ),
    ]
