# Generated by Django 2.2.27 on 2022-06-20 14:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220617_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 23, 37, 43, 289962), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='discuss_borad',
            name='command',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='discuss_borad',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 23, 37, 43, 287961), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='discuss_borad',
            name='username',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='product_borad',
            name='Create_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 23, 37, 43, 288961), help_text='create date: '),
        ),
        migrations.CreateModel(
            name='product_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.TextField(default=' ')),
                ('product_code', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app.product_code')),
            ],
        ),
    ]
