# Generated by Django 2.2.27 on 2022-06-03 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220603_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 21, 56, 14, 332119), help_text='create date: '),
        ),
    ]
