# Generated by Django 2.2.27 on 2022-06-03 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220603_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 22, 4, 31, 170999), help_text='create date: '),
        ),
    ]
