# Generated by Django 2.2.27 on 2022-06-20 14:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220620_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_borad',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product_type',
            name='product_code',
        ),
        migrations.AlterField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 23, 52, 54, 495278), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='discuss_borad',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 23, 52, 54, 493274), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='product_borad',
            name='Create_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 23, 52, 54, 494277), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='product_type',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='set_of_product_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_of_product_type', models.TextField()),
                ('product_code', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app.product_code')),
            ],
        ),
        migrations.AddField(
            model_name='product_borad',
            name='set_of_product_type',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app.set_of_product_type'),
        ),
    ]
