# Generated by Django 2.2.27 on 2022-06-03 14:39

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220603_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='saved_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 23, 39, 38, 342455), help_text='create date: '),
        ),
    ]
