# Generated by Django 2.2.27 on 2022-06-03 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220603_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 0, 48, 48, 836871), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='saved_image',
            field=models.ImageField(upload_to='upload'),
        ),
    ]
