# Generated by Django 2.2.27 on 2022-06-03 17:04

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220604_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='Save_code',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 2, 3, 58, 603848), help_text='create date: '),
        ),
    ]
