# Generated by Django 2.2.27 on 2022-06-04 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220604_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 2, 47, 48, 639223), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='saved_image',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
