# Generated by Django 2.2.27 on 2022-06-07 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220605_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Process_type', models.TextField()),
                ('Image', models.ImageField(upload_to='Pre-Image')),
            ],
        ),
        migrations.AlterField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 7, 21, 36, 59, 459444), help_text='create date: '),
        ),
    ]
