# Generated by Django 2.2.27 on 2022-06-09 14:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220609_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_import',
            name='album',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.image_album'),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 23, 42, 44, 520323), help_text='create date: '),
        ),
    ]
