# Generated by Django 2.2.27 on 2022-06-12 13:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20220609_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='discuss_borad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('product_code', models.TextField()),
                ('post_date', models.DateTimeField(default=datetime.datetime(2022, 6, 12, 22, 27, 38, 912615), help_text='create date: ')),
                ('command', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='product_images_album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 22, 27, 38, 914617), help_text='create date: '),
        ),
        migrations.CreateModel(
            name='product_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('Prodcut_image', models.ImageField(upload_to='Product_images<django.db.models.fields.TextField>')),
                ('album', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.product_images_album')),
            ],
        ),
        migrations.CreateModel(
            name='product_borad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('Create_Date', models.DateTimeField(default=datetime.datetime(2022, 6, 12, 22, 27, 38, 912615), help_text='create date: ')),
                ('Product_delta', models.TextField()),
                ('Product_image', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='app.product_image')),
                ('User_command', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app.discuss_borad')),
            ],
        ),
    ]
