# Generated by Django 2.2.27 on 2022-06-27 14:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20220623_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 23, 0, 43, 144082), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='discuss_borad',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 23, 0, 43, 140080), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='product_borad',
            name='Create_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 23, 0, 43, 140080), help_text='create date: '),
        ),
        migrations.CreateModel(
            name='product_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app.product_code')),
            ],
        ),
        migrations.CreateModel(
            name='advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=120, unique=True)),
                ('disciption', models.TextField()),
                ('product_set', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app.product_set')),
            ],
        ),
    ]
