# Generated by Django 2.2.27 on 2022-06-27 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220627_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='adv_image',
            field=models.ImageField(default='advertise/IMG_1103.JPG', upload_to='advertise/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 23, 5, 43, 464760), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='discuss_borad',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 23, 5, 43, 459757), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='product_borad',
            name='Create_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 23, 5, 43, 460757), help_text='create date: '),
        ),
    ]
