# Generated by Django 2.2.27 on 2022-06-12 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220612_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_images_album',
            name='product_name',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 23, 2, 37, 830753), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='discuss_borad',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 23, 2, 37, 828752), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='product_borad',
            name='Create_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 23, 2, 37, 828752), help_text='create date: '),
        ),
    ]
