# Generated by Django 2.2.27 on 2022-06-27 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20220627_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_set',
            name='code',
            field=models.CharField(default=123, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 23, 11, 7, 824440), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='discuss_borad',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 23, 11, 7, 819437), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='product_borad',
            name='Create_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 23, 11, 7, 820438), help_text='create date: '),
        ),
    ]
