# Generated by Django 2.2.27 on 2022-06-13 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20220612_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_borad',
            options={'permissions': (('can_add', 'add'),)},
        ),
        migrations.AlterField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 22, 21, 49, 36183), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='discuss_borad',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 22, 21, 49, 35182), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='product_borad',
            name='Create_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 22, 21, 49, 35182), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='Prodcut_image',
            field=models.ImageField(upload_to='Product_images'),
        ),
    ]
