# Generated by Django 2.2.27 on 2022-07-01 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20220627_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='adv_image',
            field=models.ImageField(default='advertise/IMG_1103.JPG', upload_to='advertise/'),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 0, 27, 36, 840374), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='discuss_borad',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 0, 27, 36, 835371), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='product_borad',
            name='Create_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 0, 27, 36, 836372), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='product_code',
            name='product_code',
            field=models.TextField(default='M10UXN3WOI5M4QUGD1GQBFW5372YQP1F', unique=True),
        ),
    ]
