# Generated by Django 2.2.27 on 2022-07-04 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20220702_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_history_set',
            name='username',
            field=models.CharField(default='admin', max_length=30),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 20, 41, 42, 96294), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='discuss_borad',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 20, 41, 42, 91290), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='product_borad',
            name='Create_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 20, 41, 42, 92291), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='product_code',
            name='product_code',
            field=models.TextField(default='K4SWRCLM0G13Z6ZU7PRJ3C64JOVL7VOK', unique=True),
        ),
    ]
