# Generated by Django 2.2.27 on 2022-07-04 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20220704_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_history',
            name='click_time',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 21, 15, 22, 62381), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 21, 15, 22, 64382), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='discuss_borad',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 21, 15, 22, 59379), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='product_borad',
            name='Create_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 21, 15, 22, 60379), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='product_code',
            name='product_code',
            field=models.TextField(default='B883BLNUKIGVEV3VAINMUY7HGOQFL42N', unique=True),
        ),
    ]
