# Generated by Django 2.2.27 on 2022-07-04 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20220704_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 22, 13, 57, 572929), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='discuss_borad',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 22, 13, 57, 568926), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='product_borad',
            name='Create_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 22, 13, 57, 568926), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='product_code',
            name='product_code',
            field=models.TextField(default='4M3BOX9ZKZPWTA4B000WZ0AZAESLWM9A', unique=True),
        ),
        migrations.AlterField(
            model_name='user_history',
            name='click_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 22, 13, 57, 570928), help_text='create date: '),
        ),
    ]
