# Generated by Django 2.2.27 on 2022-07-04 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20220704_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 22, 18, 56, 772299), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='discuss_borad',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 22, 18, 56, 768291), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='product_borad',
            name='Create_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 22, 18, 56, 768291), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='product_code',
            name='product_code',
            field=models.TextField(default='01YULA42TUWZB7AV2IKIKNB5V4Y5F4A3', unique=True),
        ),
        migrations.AlterField(
            model_name='user_history',
            name='click_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 22, 18, 56, 770280), help_text='create date: '),
        ),
    ]
