# Generated by Django 2.2.27 on 2022-07-04 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20220704_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 22, 20, 10, 673904), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='discuss_borad',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 22, 20, 10, 668900), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='product_borad',
            name='Create_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 22, 20, 10, 669901), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='product_code',
            name='product_code',
            field=models.TextField(default='R76VG1IQ709SR757V1EAMW4FSJW80THI', unique=True),
        ),
        migrations.AlterField(
            model_name='user_history',
            name='click_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 22, 20, 10, 670902), help_text='create date: '),
        ),
    ]
