# Generated by Django 2.2.27 on 2022-07-04 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20220704_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 22, 29, 56, 104261), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='discuss_borad',
            name='command',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='discuss_borad',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 22, 29, 56, 99258), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='discuss_borad',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product_borad',
            name='Create_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 22, 29, 56, 100258), help_text='create date: '),
        ),
        migrations.AlterField(
            model_name='product_code',
            name='product_code',
            field=models.TextField(default='O23J70XF0XF7LBXIWR058TS369X94XJL', unique=True),
        ),
        migrations.AlterField(
            model_name='user_history',
            name='click_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 22, 29, 56, 101259), help_text='create date: '),
        ),
    ]
